let recognition = null;
let numbersList = [];
window.SpeechRecognition = window.webkitSpeechRecognition || window.SpeechRecognition;

let isListening = false;
let currentLanguage = 'en';
let pendingExportType = null;
let wakeLock = null;
let isWakeLockEnabled = false;
let shouldRestartRecognition = false;

const translations = {
    en: {
        htmlLang: 'en',
        speechLang: 'en-US',
        locale: 'en-US',

        startRecording: 'Start Recording',
        stopRecording: 'Stop Recording',
        random50: 'Random 50%',
        resetCheckboxes: 'Reset Checkboxes',

        progressChecked: 'checked',
        consoleLog: 'Console Log',

        key: 'Key',
        keyTitle: 'Load key',
        export: 'Export',
        exportTitle: 'Export',
        import: 'Import',
        importTitle: 'Import JSON',

        exportFormatTitle: 'Export Format',
        exportFormatText: 'Choose the export format:',
        cancel: 'Cancel',
        confirm: 'Confirm',

        commentModalTitle: 'Unchecked Numbers',
        commentModalText: 'Please provide a reason for each unchecked number before exporting.',
        commentPlaceholder: 'Reason...',

        tableNumber: 'Number',
        tableCheck: 'Check',

        wakeLockSupported: 'Wake Lock is supported',
        wakeLockNotSupported: 'Wake Lock is not supported',

        keyNoValidNumbers: 'The key file contains no valid numbers.',
        keyReadError: 'The key file could not be read.',
        keyLoaded: count => `Key loaded: ${count} numbers.`,
        loadKeyFirst: 'Please load a key first.',
        allNumbersChecked: 'All numbers are already checked.',
        importedSession: date => `Imported session from ${date || 'unknown date'}`,
        invalidJson: 'Invalid JSON file.',
        speechNotSupported: 'Speech recognition is not supported in this browser.',

        defaultUncheckedReason: 'Not triggered',
        noReasonGiven: 'No reason provided',
        noComment: 'No comment',

        pdfTitle: 'MelderCheck™ - Official Export Document',
        pdfSubtitle: 'Detector Test',
        pdfDate: date => `Date: ${date}`,
        pdfIntro: 'This document was automatically generated by MelderCheck™ and documents the status of the detector numbers.',
        pdfHeaderNumber: 'Detector No.',
        pdfHeaderStatus: 'Status',
        pdfHeaderComment: 'Comment',
        pdfTriggered: 'Triggered',
        pdfNotTriggered: 'Not triggered',
        pdfCreatedAt: date => `Created on ${date}`,
        pdfPage: (page, total) => `Page ${page} of ${total}`,

        exportFileName: dateStr => `detector-test-${dateStr}`,
        commentLabelPrefix: 'No.'
    },
    de: {
        htmlLang: 'de',
        speechLang: 'de-DE',
        locale: 'de-DE',

        startRecording: 'Aufnahme starten',
        stopRecording: 'Aufnahme stoppen',
        random50: 'Zufällige 50%',
        resetCheckboxes: 'Checkboxen zurücksetzen',

        progressChecked: 'geprüft',
        consoleLog: 'Konsolenprotokoll',

        key: 'Key',
        keyTitle: 'Key laden',
        export: 'Export',
        exportTitle: 'Export',
        import: 'Import',
        importTitle: 'JSON importieren',

        exportFormatTitle: 'Exportformat',
        exportFormatText: 'Wählen Sie das Exportformat:',
        cancel: 'Abbrechen',
        confirm: 'Bestätigen',

        commentModalTitle: 'Nicht geprüfte Nummern',
        commentModalText: 'Bitte geben Sie vor dem Export für jede nicht geprüfte Nummer einen Grund an.',
        commentPlaceholder: 'Grund...',

        tableNumber: 'Nummer',
        tableCheck: 'Prüfen',

        wakeLockSupported: 'Wake Lock wird unterstützt',
        wakeLockNotSupported: 'Wake Lock wird nicht unterstützt',

        keyNoValidNumbers: 'Die Key-Datei enthält keine gültigen Nummern.',
        keyReadError: 'Key-Datei konnte nicht gelesen werden.',
        keyLoaded: count => `Key geladen: ${count} Nummern.`,
        loadKeyFirst: 'Bitte zuerst einen Key laden.',
        allNumbersChecked: 'Alle Nummern sind bereits markiert.',
        importedSession: date => `Importierte Sitzung vom ${date || 'unbekanntes Datum'}`,
        invalidJson: 'Ungültige JSON-Datei.',
        speechNotSupported: 'Spracherkennung wird in diesem Browser nicht unterstützt.',

        defaultUncheckedReason: 'Nicht ausgelöst',
        noReasonGiven: 'Kein Grund angegeben',
        noComment: 'Kein Kommentar',

        pdfTitle: 'MelderCheck™ - Offizielles Exportdokument',
        pdfSubtitle: 'Melder-Probe',
        pdfDate: date => `Datum: ${date}`,
        pdfIntro: 'Mit diesem Dokument dokumentiert MelderCheck™ den Prüfstatus der Melder-Nummern.',
        pdfHeaderNumber: 'Melder Nr.',
        pdfHeaderStatus: 'Status',
        pdfHeaderComment: 'Kommentar',
        pdfTriggered: 'Ausgelöst',
        pdfNotTriggered: 'Nicht ausgelöst',
        pdfCreatedAt: date => `Erstellt am ${date}`,
        pdfPage: (page, total) => `Seite ${page} von ${total}`,

        exportFileName: dateStr => `bewegungsmelder-test-${dateStr}`,
        commentLabelPrefix: 'Nr.'
    }
};

const wordToNumber = {
    'one': 1, 'won': 1,
    'two': 2, 'to': 2, 'too': 2,
    'three': 3,
    'four': 4, 'for': 4,
    'five': 5,
    'six': 6,
    'seven': 7,
    'eight': 8, 'ate': 8,
    'nine': 9,
    'ten': 10,
    'eleven': 11,
    'twelve': 12,
    'thirteen': 13,
    'fourteen': 14,
    'fifteen': 15,
    'sixteen': 16,
    'seventeen': 17,
    'eighteen': 18,
    'nineteen': 19,
    'twenty': 20,
    'thirty': 30,
    'forty': 40, 'fourty': 40,
    'fifty': 50,
    'sixty': 60,
    'seventy': 70,
    'eighty': 80,
    'ninety': 90,
    'hundred': 100,
    'ein': 1, 'eins': 1, 'zwei': 2, 'drei': 3, 'vier': 4, 'fünf': 5, 'fuenf': 5,
    'sechs': 6, 'sieben': 7, 'acht': 8, 'neun': 9, 'zehn': 10,
    'elf': 11, 'zwölf': 12, 'zwoelf': 12, 'dreizehn': 13, 'vierzehn': 14,
    'fünfzehn': 15, 'fuenfzehn': 15, 'sechzehn': 16, 'siebzehn': 17, 'achtzehn': 18,
    'neunzehn': 19, 'zwanzig': 20, 'dreißig': 30, 'dreissig': 30, 'vierzig': 40,
    'fünfzig': 50, 'fuenfzig': 50, 'sechzig': 60, 'siebzig': 70, 'achtzig': 80,
    'neunzig': 90, 'hundert': 100
};

const langSwitch = document.getElementById('langSwitch');
const labelEN = document.getElementById('lang-label-en');
const labelDE = document.getElementById('lang-label-de');

function t() {
    return translations[currentLanguage];
}

function normalizeTranscript(text) {
    return text
        .toLowerCase()
        .split(/\s+/)
        .map(word => wordToNumber[word] !== undefined ? wordToNumber[word] : word)
        .join(' ');
}

function setText(id, value) {
    const el = document.getElementById(id);
    if (el) el.innerText = value;
}

function setTitle(id, value) {
    const el = document.getElementById(id);
    if (el) el.title = value;
}

function syncModalScrollLock() {
    const anyOpen = document.querySelector('dialog[open]');
    document.documentElement.classList.toggle('modal-open', !!anyOpen);
}

document.querySelectorAll('dialog').forEach(dialog => {
    dialog.addEventListener('close', syncModalScrollLock);
    dialog.addEventListener('cancel', syncModalScrollLock);
});

function syncLanguagePill() {
    if (!langSwitch || !labelEN || !labelDE) return;

    const isGerman = currentLanguage === 'de';
    langSwitch.classList.toggle('de', isGerman);
    langSwitch.setAttribute('aria-checked', String(isGerman));
    labelEN.classList.toggle('active', !isGerman);
    labelDE.classList.toggle('active', isGerman);
}

function applyLanguage() {
    const lang = t();

    document.documentElement.lang = lang.htmlLang;
    document.title = 'AudioMarker';

    setText('start-recognition', isListening ? lang.stopRecording : lang.startRecording);
    setText('random-check', lang.random50);
    setText('reset-checkboxes', lang.resetCheckboxes);

    setText('console-log', lang.consoleLog);

    setText('key-label-text', lang.key);
    setTitle('key-label', lang.keyTitle);
    setText('export-btn-text', lang.export);
    setTitle('export-btn', lang.exportTitle);
    setText('import-label-text', lang.import);
    setTitle('import-label', lang.importTitle);

    setText('export-format-title', lang.exportFormatTitle);
    setText('export-format-text', lang.exportFormatText);
    setText('export-json-btn', 'JSON');
    setText('export-pdf-btn', 'PDF');
    setText('export-format-cancel', lang.cancel);

    setText('comment-modal-title', lang.commentModalTitle);
    setText('comment-modal-text', lang.commentModalText);
    setText('comment-cancel', lang.cancel);
    setText('comment-confirm', lang.confirm);

    setText('table-header-number', lang.tableNumber);
    setText('table-header-check', lang.tableCheck);

    setText(
        'wakeLockAPIAvailable',
        'wakeLock' in navigator ? lang.wakeLockSupported : lang.wakeLockNotSupported
    );

    const commentInputs = document.querySelectorAll('#comment-list input');
    commentInputs.forEach(input => {
        input.placeholder = lang.commentPlaceholder;
    });

    const commentLabels = document.querySelectorAll('#comment-list label[data-number]');
    commentLabels.forEach(label => {
        label.innerText = `${lang.commentLabelPrefix} ${label.dataset.number}`;
    });

    syncLanguagePill();
    updateProgress();
}

function updateProgress() {
    const total = numbersList.length;
    const checked = numbersList.filter(n => {
        const cb = document.getElementById('check-' + n);
        return cb && cb.checked;
    }).length;

    const progressLabel = document.getElementById('progress-label');
    const progressBarFill = document.getElementById('progress-bar-fill');

    if (progressLabel) {
        progressLabel.innerText = `${checked} / ${total} ${t().progressChecked}`;
    }

    if (progressBarFill) {
        progressBarFill.style.width = `${total ? (checked / total) * 100 : 0}%`;
        progressBarFill.style.background =
            checked === total && total > 0
                ? 'linear-gradient(90deg, #f5c400, #ffe066)'
                : 'linear-gradient(90deg, #35D49F, #05EB20)';
    }
}

function vibrate() {
    if ('vibrate' in navigator) navigator.vibrate(50);
}

function playSuccessSound() {
    const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    const oscillator = audioCtx.createOscillator();
    const gainNode = audioCtx.createGain();

    oscillator.connect(gainNode);
    gainNode.connect(audioCtx.destination);

    oscillator.type = 'sine';
    oscillator.frequency.setValueAtTime(880, audioCtx.currentTime);
    oscillator.frequency.setValueAtTime(1100, audioCtx.currentTime + 0.1);
    gainNode.gain.setValueAtTime(0.4, audioCtx.currentTime);
    gainNode.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.4);

    oscillator.start(audioCtx.currentTime);
    oscillator.stop(audioCtx.currentTime + 0.4);
}

function playUnrecognizedSound() {
    const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    const oscillator = audioCtx.createOscillator();
    const gainNode = audioCtx.createGain();

    oscillator.connect(gainNode);
    gainNode.connect(audioCtx.destination);

    oscillator.type = 'sawtooth';
    oscillator.frequency.setValueAtTime(300, audioCtx.currentTime);
    oscillator.frequency.setValueAtTime(200, audioCtx.currentTime + 0.15);
    gainNode.gain.setValueAtTime(0.3, audioCtx.currentTime);
    gainNode.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.4);

    oscillator.start(audioCtx.currentTime);
    oscillator.stop(audioCtx.currentTime + 0.4);
}

function renderTable() {
    const tbody = document.getElementById('number-table-body');
    if (!tbody) return;

    tbody.innerHTML = '';

    numbersList.forEach(number => {
        const tr = document.createElement('tr');
        tr.dataset.number = String(number);

        const tdNumber = document.createElement('td');
        tdNumber.textContent = number;

        const tdCheck = document.createElement('td');
        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.id = `check-${number}`;

        checkbox.addEventListener('change', () => {
            tr.classList.toggle('checked-row', checkbox.checked);
            updateProgress();
        });

        tdCheck.appendChild(checkbox);
        tr.appendChild(tdNumber);
        tr.appendChild(tdCheck);
        tbody.appendChild(tr);
    });

    updateProgress();
}

function parseKeyText(text) {
    const tokens = text.split(/[\s,;]+/).map(t => t.trim()).filter(Boolean);
    const parsed = tokens
        .map(t => parseInt(t, 10))
        .filter(n => !isNaN(n));

    return [...new Set(parsed)].sort((a, b) => a - b);
}

document.getElementById('key-file')?.addEventListener('change', event => {
    const file = event.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = e => {
        try {
            const text = String(e.target.result || '');
            const parsedNumbers = parseKeyText(text);

            if (!parsedNumbers.length) {
                alert(t().keyNoValidNumbers);
                return;
            }

            numbersList = parsedNumbers;
            renderTable();
            alert(t().keyLoaded(numbersList.length));
        } catch {
            alert(t().keyReadError);
        }
    };

    reader.readAsText(file);
    event.target.value = '';
});

function ensureRecognition() {
    if (recognition) return recognition;
    if (!(window.SpeechRecognition || window.webkitSpeechRecognition)) return null;

    recognition = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
    recognition.continuous = true;
    recognition.interimResults = false;
    recognition.lang = t().speechLang;

    recognition.onresult = event => {
        const result = event.results[event.results.length - 1][0].transcript;
        const output = document.getElementById('output');
        if (output) output.innerText = result;
        markNumberAsChecked(result);
    };

    recognition.onend = () => {
        if (shouldRestartRecognition && isListening) {
            setTimeout(() => {
                try {
                    recognition.lang = t().speechLang;
                    recognition.start();
                } catch {}
            }, 150);
        }
    };

    recognition.onerror = () => {};

    return recognition;
}

async function toggleRecognition() {
    if (!numbersList.length) {
        alert(t().loadKeyFirst);
        return;
    }

    const instance = ensureRecognition();
    if (!instance) {
        alert(t().speechNotSupported);
        return;
    }

    if (!isListening) {
        try {
            instance.lang = t().speechLang;
            shouldRestartRecognition = true;
            instance.start();
            isListening = true;
        } catch {}
    } else {
        shouldRestartRecognition = false;
        isListening = false;
        try {
            instance.stop();
        } catch {}
    }

    applyLanguage();
}

function toggleLanguage() {
    currentLanguage = currentLanguage === 'en' ? 'de' : 'en';
    applyLanguage();

    if (recognition) {
        recognition.lang = t().speechLang;
    }

    if (isListening && recognition) {
        shouldRestartRecognition = false;
        try {
            recognition.stop();
        } catch {}

        setTimeout(() => {
            if (isListening && recognition) {
                try {
                    recognition.lang = t().speechLang;
                    shouldRestartRecognition = true;
                    recognition.start();
                } catch {}
            }
        }, 200);
    }
}

function markNumberAsChecked(text) {
    const normalizedText = normalizeTranscript(text);
    const numbers = normalizedText.match(/\d+/g);
    let matched = false;

    if (numbers) {
        for (const numberStr of numbers) {
            const number = parseInt(numberStr, 10);
            if (!isNaN(number) && numbersList.includes(number)) {
                const checkbox = document.getElementById('check-' + number);
                if (checkbox && !checkbox.checked) {
                    checkbox.checked = true;
                    checkbox.closest('tr')?.classList.add('checked-row');
                    playSuccessSound();
                    vibrate();
                    checkbox.closest('tr')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
                    updateProgress();
                    matched = true;
                }
            }
        }
    }

    if (!matched) playUnrecognizedSound();
}

document.getElementById('start-recognition')?.addEventListener('click', async () => {
    await toggleWakeLock();
    await toggleRecognition();
});

document.getElementById('langSwitch')?.addEventListener('click', toggleLanguage);

document.getElementById('reset-checkboxes')?.addEventListener('click', () => {
    for (const number of numbersList) {
        const checkbox = document.getElementById('check-' + number);
        if (checkbox && checkbox.checked) {
            checkbox.checked = false;
            checkbox.closest('tr')?.classList.remove('checked-row');
        }
    }
    updateProgress();
});

function buildSessionData(comments = {}) {
    const now = new Date();
    const checked = [];
    const unchecked = [];

    for (const number of numbersList) {
        const cb = document.getElementById('check-' + number);
        if (cb && cb.checked) {
            checked.push(number);
        } else {
            unchecked.push({
                number,
                reason: comments[number] || t().defaultUncheckedReason
            });
        }
    }

    return {
        language: currentLanguage,
        exportedAt: now.toISOString(),
        exportedAtReadable: now.toLocaleString(t().locale),
        complete: unchecked.length === 0,
        numbers: [...numbersList],
        checked,
        unchecked
    };
}

function doExportJSON(comments = {}) {
    const data = buildSessionData(comments);
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const dateStr = new Date().toISOString().slice(0, 10);

    a.href = url;
    a.download = `${t().exportFileName(dateStr)}.json`;
    a.click();

    URL.revokeObjectURL(url);
}

function doExportPDF(comments = {}) {
    const data = buildSessionData(comments);
    const lang = translations[data.language] || t();
    const { jsPDF } = window.jspdf;

    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const pageHeight = doc.internal.pageSize.height;
    const pageWidth = doc.internal.pageSize.width;
    const marginBottom = 15;
    const marginTop = 20;

    function addHeader(yPosition) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.text(lang.pdfHeaderNumber, 25, yPosition);
        doc.text(lang.pdfHeaderStatus, 70, yPosition);
        doc.text(lang.pdfHeaderComment, 120, yPosition);
        doc.setLineWidth(0.5);
        doc.line(20, yPosition + 2, 190, yPosition + 2);
        doc.setFont('helvetica', 'normal');
        return yPosition + 8;
    }

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(lang.pdfTitle, 105, 20, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(lang.pdfSubtitle, 105, 28, { align: 'center' });
    doc.text(lang.pdfDate(data.exportedAtReadable), 105, 35, { align: 'center' });

    doc.setFontSize(10);
    doc.text(lang.pdfIntro, 20, 45);

    let yPos = addHeader(55);

    for (const number of data.checked) {
        if (yPos + 7 > pageHeight - marginBottom) {
            doc.addPage();
            yPos = addHeader(marginTop);
        }
        doc.text(String(number), 25, yPos);
        doc.text(`✓ ${lang.pdfTriggered}`, 70, yPos);
        doc.text('—', 120, yPos);
        yPos += 7;
    }

    for (const item of data.unchecked) {
        const comment = item.reason || lang.noComment;
        const lines = doc.splitTextToSize(comment, 65);
        const lineHeight = lines.length * 5;
        const rowHeight = Math.max(7, lineHeight);

        if (yPos + rowHeight > pageHeight - marginBottom) {
            doc.addPage();
            yPos = addHeader(marginTop);
        }

        doc.text(String(item.number), 25, yPos);
        doc.text(`✗ ${lang.pdfNotTriggered}`, 70, yPos);
        doc.text(lines, 120, yPos);
        yPos += rowHeight;
    }

    const totalPages = doc.internal.getNumberOfPages();

    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.text(lang.pdfCreatedAt(data.exportedAtReadable), 20, pageHeight - 10);
        doc.text(lang.pdfPage(i, totalPages), pageWidth - 20, pageHeight - 10, { align: 'right' });
    }

    const dateStr = new Date().toISOString().slice(0, 10);
    doc.save(`${lang.exportFileName(dateStr)}.pdf`);
}

document.getElementById('export-btn')?.addEventListener('click', () => {
    if (!numbersList.length) {
        alert(t().loadKeyFirst);
        return;
    }
    document.getElementById('export-format-modal')?.showModal();
    syncModalScrollLock();
});

document.getElementById('export-format-cancel')?.addEventListener('click', () => {
    document.getElementById('export-format-modal')?.close();
});

document.getElementById('export-json-btn')?.addEventListener('click', () => {
    document.getElementById('export-format-modal')?.close();

    const allChecked = numbersList.every(n => {
        const cb = document.getElementById('check-' + n);
        return cb && cb.checked;
    });

    if (allChecked) {
        doExportJSON();
    } else {
        pendingExportType = 'json';
        openCommentModal();
    }
});

document.getElementById('export-pdf-btn')?.addEventListener('click', () => {
    document.getElementById('export-format-modal')?.close();

    const allChecked = numbersList.every(n => {
        const cb = document.getElementById('check-' + n);
        return cb && cb.checked;
    });

    if (allChecked) {
        doExportPDF();
    } else {
        pendingExportType = 'pdf';
        openCommentModal();
    }
});

function openCommentModal() {
    const unchecked = numbersList.filter(n => {
        const cb = document.getElementById('check-' + n);
        return !(cb && cb.checked);
    });

    const commentList = document.getElementById('comment-list');
    if (!commentList) return;

    commentList.innerHTML = unchecked.map(n => `
        <div class="comment-row">
            <label for="comment-${n}" data-number="${n}">${t().commentLabelPrefix} ${n}</label>
            <input type="text" id="comment-${n}" placeholder="${t().commentPlaceholder}" />
        </div>
    `).join('');

    document.getElementById('comment-modal')?.showModal();
    syncModalScrollLock();
}

function getComments() {
    const comments = {};
    const unchecked = numbersList.filter(n => {
        const cb = document.getElementById('check-' + n);
        return !(cb && cb.checked);
    });

    for (const n of unchecked) {
        const input = document.getElementById('comment-' + n);
        if (input) comments[n] = input.value.trim() || t().noReasonGiven;
    }

    return comments;
}

document.getElementById('comment-confirm')?.addEventListener('click', () => {
    const comments = getComments();
    document.getElementById('comment-modal')?.close();

    if (pendingExportType === 'json') {
        doExportJSON(comments);
    } else if (pendingExportType === 'pdf') {
        doExportPDF(comments);
    }

    pendingExportType = null;
});

document.getElementById('comment-cancel')?.addEventListener('click', () => {
    document.getElementById('comment-modal')?.close();
    pendingExportType = null;
});

document.getElementById('import-json')?.addEventListener('change', event => {
    const file = event.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = e => {
        try {
            const data = JSON.parse(e.target.result);

            if (data.language && translations[data.language]) {
                currentLanguage = data.language;
            }

            if (Array.isArray(data.numbers)) {
                numbersList = [...new Set(
                    data.numbers
                        .map(n => parseInt(n, 10))
                        .filter(n => !isNaN(n))
                )].sort((a, b) => a - b);

                renderTable();
            }

            for (const number of numbersList) {
                const cb = document.getElementById('check-' + number);
                if (cb) {
                    cb.checked = false;
                    cb.closest('tr')?.classList.remove('checked-row');
                }
            }

            if (data.checked && Array.isArray(data.checked)) {
                for (const number of data.checked) {
                    const cb = document.getElementById('check-' + number);
                    if (cb) {
                        cb.checked = true;
                        cb.closest('tr')?.classList.add('checked-row');
                    }
                }
            }

            applyLanguage();
            updateProgress();
            alert(t().importedSession(data.exportedAtReadable));
        } catch {
            alert(t().invalidJson);
        }
    };

    reader.readAsText(file);
    event.target.value = '';
});

async function toggleWakeLock() {
    try {
        if (isWakeLockEnabled) {
            if (wakeLock) {
                await wakeLock.release();
                wakeLock = null;
            }
            isWakeLockEnabled = false;
        } else {
            if (!wakeLock && 'wakeLock' in navigator) {
                wakeLock = await navigator.wakeLock.request('screen');
                wakeLock.addEventListener('release', () => {
                    wakeLock = null;
                    isWakeLockEnabled = false;
                    applyLanguage();
                });
                isWakeLockEnabled = true;
            }
        }
    } catch {}

    applyLanguage();
}

document.querySelector('h1')?.addEventListener('click', () => {
    const consoleLog = document.getElementById('console-log');
    const output = document.getElementById('output');
    const randomCheck = document.getElementById('random-check');

    if (consoleLog && output) {
        consoleLog.classList.toggle('hidden');
        output.classList.toggle('hidden');
    }

    if (randomCheck) {
        randomCheck.classList.toggle('hidden');
    }
});

function shuffleArray(array) {
    const arr = [...array];
    for (let i = arr.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
}

function randomCheckHalf() {
    if (!numbersList.length) {
        alert(t().loadKeyFirst);
        return;
    }

    const remaining = numbersList.filter(number => {
        const checkbox = document.getElementById('check-' + number);
        return checkbox && !checkbox.checked;
    });

    if (!remaining.length) {
        alert(t().allNumbersChecked);
        return;
    }

    const amountToAdd = Math.ceil(remaining.length / 2);
    const selected = shuffleArray(remaining).slice(0, amountToAdd);

    for (const number of selected) {
        const checkbox = document.getElementById('check-' + number);
        if (checkbox) {
            checkbox.checked = true;
            checkbox.closest('tr')?.classList.add('checked-row');
        }
    }

    updateProgress();
}

document.getElementById('random-check')?.addEventListener('click', randomCheckHalf);

applyLanguage();
updateProgress();
